---
env:
  pre_settings:
    - { name: '$settings["hash_salt"]', status: true, value: '1N26qj6mgJF6BpGU_Flo4SLiA72DCZMRd-WkCInvTd3VumZoxvGK_torzbh6JgHg010jkiL3HQ'}
    - { name: '$databases["amm_source"]["default"]["database"]', status: true, value: '{{ old_source_db_name }}' }
    - { name: '$databases["amm_source"]["default"]["username"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["password"]', status: true, value: 'root' }
    - { name: '$databases["amm_source"]["default"]["host"]', status: true, value: '127.0.0.1' }
    - { name: '$databases["amm_source"]["default"]["namespace"]', status: true, value: 'Drupal\\\\Core\\\\Database\\\\Driver\\\\mysql' }
    - { name: '$databases["amm_source"]["default"]["driver"]', status: true, value: 'mysql' }
    - { name: '$config_directories["staging"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$config_directories["sync"]', status: true, value: 'sites/default/config/staging' }
    - { name: '$settings["install_profile"]', status: true, value: 'openy' }
    - { name: '$config["system.file"]["path"]["temporary"]', status: true, value: '/tmp' }
    - { name: '$settings["memcache"]["bins"]', status: false, value: '[\\"default\\" => \\"default\\"]' }
    - { name: '$settings["memcache"]["key_prefix"]', status: false, value: '{{ mysql_db }}' }
    - { name: '$settings["cache"]["default"]', status: false, value: 'cache.backend.memcache' }
    - { name: '$databases["default"]["default"]["sql_mode"]', status: false, value: 'TRADITIONAL'}
  pre_drush_commands:
    - { name: 'en', status: true, arguments: "openy_upgrade_tool -y" }
    - { name: 'cr', status: true, arguments: "" }
  shell_commands:
    - { name: 'Update Drupal Entities', status: true, arguments: "drush entup -y || true"}
    - { name: 'Clear cache', status: true, arguments: "drush cr" }
    - { name: 'Update Drupal DB', status: true, arguments: "drush updatedb -y || true"}
  modules:
    - { name: 'dblog stage_file_proxy', status: true }
  drush_commands:
    - { name: 'user-password', status: true, arguments: "{{ drupal_user }} --password={{ drupal_pass }}" }
    - { name: 'config-set', status: true, arguments: "system.site uuid 97eff2a4-ba00-4bd3-b64c-7641d6ccb54c -y" }
    - { name: 'config-set', status: true, arguments: "system.file path.temporary /tmp -y" }
    - { name: 'config-set', status: true, arguments: "mailsystem.settings defaults.sender SMTPMailSystem" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_on 1" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_port 1025" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_protocol standard" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_username ''" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_password ''" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_host demo.cibox.tools" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_from from_www_smtp@localhost.com" }
    - { name: 'config-set', status: true, arguments: "smtp.settings smtp_fromname 'Testing Emails'" }
    - { name: 'config-import', status: false, arguments: "staging -y --partial" }
    - { name: 'ciboxcr', status: true, arguments: "" }
    - { name: 'cr', status: true, arguments: "" }
    - { name: 'migrate-import', status: false, arguments: "--group=ymca --force" }
    - { name: 'search-api-reindex', status: false, arguments: "" }
    - { name: 'search-api-index', status: false, arguments: "" }
    - { name: 'search-index', status: false, arguments: "" }
    - { name: 'config-set', status: true, arguments: "shield.config enabled 1" }
    - { name: 'config-set', status: true, arguments: "shield.config login admin" }
    - { name: 'config-set', status: true, arguments: "shield.config password cibox" }
    # To fix configuration problem let's install the module here.
    - { name: 'en', status: false, arguments: "yptf_master" }
  post_settings:
    - { name: '$settings["cache"]["bins"]["render"]', status: false, value: 'cache.backend.memory' }
    - { name: '$config["stage_file_proxy.settings"]["origin"]', status: true, value: '{{ origin_site_url }}' }
